name: Create Bump Version Pull Request

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        required: true
        description: 'Version number to bump'
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install `cargo-edit`
        run: cargo install cargo-edit
      
      - id: cargo-set-version
        name: Set Version
        run: cargo set-version --bump ${{ inputs.version }}

      - name: Set Crate Version as Environment Variable
        run: |
          CARGO_TOML_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/[\"]/, "", $2); printf("%s",$2) }' Cargo.toml)
          echo "CRATE_VERSION=$CARGO_TOML_VERSION" >> $GITHUB_ENV

      - name: Create Commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b "chore/bump-version-v$CRATE_VERSION"
          git add .
          git tag -a -m "chore: bump version to v$CRATE_VERSION" "v$CRATE_VERSION"
          git commit -m "chore: bump version to v$CRATE_VERSION"

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.pulls.create({
              title: 'chore: bump version to `${{ inputs.version }}`',
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "chore/bump-version-v$CRATE_VERSION",
              base: 'main',
              body: '### Release `${{ inputs.version }}`\n\nCreated by @${{ github.actor }} via ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.'
            });
            return response.data.number;

      - name: Report Error
        if: steps.cargo-set-version.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{steps.create-pull-request.outputs.result}},
              body: '## 🚨 An error ocurred executing `cargo set-version ${{ inputs.version }}`',
            })